Repository astropy/specutils, pull requests merged in 2022-08, with the labels that each got.

#971 TST: Fix code style job
  specutils/io/default_loaders/wcs_fits.py
Labels: testing

#970 Fix moment with order > 1 and non-square spatial dimensions
  CHANGES.rst
  specutils/analysis/moment.py
  specutils/tests/test_analysis.py
Labels: bug

#973 Add workaround for GWCS error in some JWST IFU cubes
  CHANGES.rst
  specutils/io/default_loaders/jwst_reader.py
Labels: bug, io

#954 DOC: Do not use code that emits warning in example
  docs/spectrum1d.rst
Labels: docs
