Repository astropy/specutils, pull requests merged in 2023-09, with the labels that each got.

#1079 Compatibility with unreleased ASDF stack for JWST s2d data
  conftest.py
  specutils/io/default_loaders/jwst_reader.py
Labels: bug

#1081 Debug devdeps
  specutils/tests/test_spectrum1d.py
  tox.ini
Labels: testing, bug

#1086 Update devdeps tests to use more recent python, numpy
  .github/workflows/ci_workflows.yml
  tox.ini
Labels: testing

#1088 Correct velocity_convention options in Spectrum1D docstring
  specutils/spectra/spectrum1d.py
Labels: docs
