Repository astropy/specutils, pull requests merged in 2023-11, with the labels that each got.

#1093 TST: Pin casa-formats-io in oldest-deps
  tox.ini
Labels: testing

#1095 Replace tmpdir with tmp_path
  specutils/io/default_loaders/tests/test_apogee.py
  specutils/io/default_loaders/tests/test_jwst_reader.py
  specutils/tests/test_io.py
Labels: testing

#1110 Update contributor docs
  docs/contributing.rst
  setup.cfg
Labels: docs

#1111 TST: Fix devdeps and clean up matrix
  .github/workflows/ci_workflows.yml
  docs/analysis.rst
  docs/spectral_cube.rst
  pyproject.toml
  setup.cfg
  tox.ini
Labels: testing

#1115 Update Weekly CI
  .github/workflows/ci_cron_weekly.yml
Labels: testing, Extra CI
