Repository astropy/specutils, pull requests merged in 2023-03, with the labels that each got.

#1032 Replace deprecated AsdfInFits
  setup.cfg
  specutils/io/default_loaders/tests/test_jwst_reader.py
  specutils/tests/test_io.py
  specutils/tests/test_loaders.py
  tox.ini
Labels: testing

#1009 Fix and extend `wcs1d-fits` loader for multi-D WCS
  specutils/io/default_loaders/wcs_fits.py
  specutils/tests/test_loaders.py
Labels: bug, io, spectral-cube

#1050 Fix bad unit string in some JWST headers to avoid a UnitWarning on read
  CHANGES.rst
  specutils/io/default_loaders/jwst_reader.py
Labels: io
