Repository astropy/specutils, pull requests merged in 2023-02, with the labels that each got.

#1015 Pin matplotlib in oldestdeps job
  .github/workflows/ci_workflows.yml
  tox.ini
Labels: testing, bug

#1020 RTD: Use mamba to pick up new graphviz
  .readthedocs.yml
  docs/rtd_environment.yaml
Labels: bug, docs

#1019 Unignore and fix doctest
  docs/arithmetic.rst
  docs/fitting.rst
  docs/index.rst
  docs/manipulation.rst
  docs/spectral_cube.rst
  docs/spectral_regions.rst
  docs/spectrum1d.rst
  specutils/manipulation/model_replace.py
  specutils/manipulation/resample.py
Labels: testing, docs

#1022 Catch deprecation from AsdfExtension
  specutils/io/asdf/extension.py
Labels: testing

#1017 basic code example and links to Spectrum1D.write
  docs/custom_loading.rst
  docs/spectrum1d.rst
Labels: docs

#1024 Catch deprecation warning for ASDF entry point
  setup.cfg
Labels: testing

#1025 change asdf.tests.helpers uses to asdf.testing.helpers
  specutils/io/asdf/tags/tests/test_spectra.py
Labels: testing

#1026 TST: Pin dask in oldest deps job because it is upgrading numpy
  tox.ini
Labels: testing
