Repository astropy/specutils, pull requests merged in 2024-05, with the labels that each got.

#1136 TST: Change SDSS URLs to HTTPS
  specutils/tests/test_loaders.py
Labels: testing, bug, io

#1138 Separate out the codecov upload to a separate job in CI
  .github/workflows/ci_workflows.yml
Labels: testing

#1141 Fix moment calculations
  docs/analysis.rst
  docs/spectral_cube.rst
  specutils/analysis/moment.py
  specutils/tests/test_analysis.py
Labels: bug, analysis
