Repository astropy/specutils, pull requests merged in 2024-12, with the labels that each got.

#1199 Use exact domain limits for polynomial wavelength solutions in _read_non_linear_iraf_wcs
  CHANGES.rst
  specutils/io/default_loaders/wcs_fits.py
  specutils/tests/test_loaders.py
Labels: bug, io

#1200 Ignore deprecation warnings coming from upstream gwcs package
  specutils/tests/test_loaders.py
Labels: testing, no-changelog-entry-needed

#1207 Fix for gwcs inverse transform with a bounding_box (try 2)
  specutils/tests/test_spectrum1d.py
Labels: no-changelog-entry-needed

#1194 Reverts PR 1193 (Ignore GwcsBoundingBoxWarning in JWST readers)
  specutils/io/default_loaders/jwst_reader.py
Labels: no-changelog-entry-needed

#1208 Revert "Ignore deprecation warnings coming from upstream gwcs package"
  specutils/tests/test_loaders.py
Labels: testing, no-changelog-entry-needed
