Repository astropy/specutils, pull requests merged in 2025-07, with the labels that each got.

#1248 Update URL for muscles test file
  specutils/tests/test_loaders.py
Labels: testing, no-changelog-entry-needed

#1250 TST: Use dev spectral-cube in devdeps
  tox.ini
Labels: testing, no-changelog-entry-needed

#1255 Fix codecov upload issue
  .github/workflows/ci_workflows.yml
Labels: testing, no-changelog-entry-needed, github_actions

#1257 Fixed missing space in error message
  specutils/io/default_loaders/wcs_fits.py
Labels: no-changelog-entry-needed
